### ISSUE TITLE
hpc-carpentry logo

### ISSUE THREAD

**Issue by psteinb** [hpc-carpentry/hpc-carpentry.old-site#28]
As noted in #26, we would love to have a better logo than
![hpc-carpentry](https://user-images.githubusercontent.com/1465603/96255164-bdefb580-0fb6-11eb-8367-3a2ba19915cb.png)
even though @ocaisa did a great job coming up with it. Please provide drafts and receive eternal gratefulness by a growing community. 

*Here to vote?* Click [here](#issuecomment-729227473) to jump down!

**Comment by tkphd** [comment]
Can we hire an artist to show us how it's done?

Reference banners:

![Software Carpentry](https://github.com/carpentries/styles/raw/gh-pages/assets/img/swc-logo-blue.svg)

![Data Carpentry](https://github.com/carpentries/styles/raw/gh-pages/assets/img/dc-logo-black.svg)

![Library Carpentry](https://github.com/carpentries/styles/raw/gh-pages/assets/img/lc-logo-black.svg)

**Comment by reid-a** [comment]
A parallel array of hammers, nailing a bunch of boards together at once?

**Comment by ocaisa** [comment]
I made a pass at this today, making the analogy that HPC is brining in the heavy machinery:
![HPC Carpentry](https://github.com/ocaisa/hpc-carpentry.org/raw/main/assets/img/hpc-carpentry.png)

**Comment by ChristinaLK** [comment]
If people like this, I can make a more passable digital version. 

![Photo on 10-23-20 at 11 08 AM #2](https://user-images.githubusercontent.com/4634021/97027524-77eba200-1520-11eb-8b7a-bb6c329fad7e.jpg)

**Comment by psteinb** [comment]
I like both designs from https://github.com/hpc-carpentry/hpc-carpentry.github.io/issues/28#issuecomment-713418926 and https://github.com/hpc-carpentry/hpc-carpentry.github.io/issues/28#issuecomment-715436450. Can we have a hybrid?

**Comment by tkphd** [comment]
@annajiat has offered to spread the word among his students that we're looking for artwork; hopefully, we'll get a nibble in the next month or so. We should expect this to be an iterative process. The goal is to give the artist something to go on, but let their imagination & skills run with it.

Vague request: 

- We want a wide-format banner, a square-format logo, and icons. Similarity in professional-ness and palette to the [SW Carpentry page](https://software-carpentry.org) is desirable.
- Other Carpentries' artwork comprises the name in decent-looking font, with some characters replaced with tools, or with tools decorating the borders. Example tools include a hammer & nail, C-clamp, T-square.
- The concept that HPC brings the power is nice. Excavators require extensive training, perhaps licensing, though, and that's probably not the right message. Something intermediate, like a power drill or circular saw might set a better tone: you shouldn't go straight for them, but after an hour's training, you're good to go.

**Comment by annajiat** [comment]
Hi everyone,

Please find of some proposals for HPC Carpentry Banner, Logo and Icons at https://drive.google.com/drive/u/0/folders/1WDS6qZMFhG-Z1xtThOPFkmSiw1huO4-Y

Looking forward to your feedback,
best regards,
Annajiat

**Comment by tkphd** [comment]
Wow @annajiat, there are a lot of good designs here! Amazing! Looking forward to discussing during tomorrow's Coworking Hours.

**Comment by tkphd** [comment]
## Voting on Logos

The following comments represent the current HPC Carpentry Banner submissions. Please vote on each using the thumbs up & down emoji according to your preference. You can (and should) vote on multiple options, but please do not vote from more than one account.

**Comment by tkphd** [comment]
@ocaisa

 ![](https://github.com/ocaisa/hpc-carpentry.org/raw/main/assets/img/hpc-carpentry.svg)

**Comment by tkphd** [comment]
@ChristinaLK 

![](https://user-images.githubusercontent.com/4634021/97027524-77eba200-1520-11eb-8b7a-bb6c329fad7e.jpg)

**Comment by tkphd** [comment]
@ocaisa 2

![](https://user-images.githubusercontent.com/1465603/96255164-bdefb580-0fb6-11eb-8367-3a2ba19915cb.png)

**Comment by tkphd** [comment]
Md Sabbir al Mamon via @annajiat

![md_sabbir_al_mamon](https://user-images.githubusercontent.com/2179347/99453723-6022f600-28f3-11eb-8b34-76c52280111b.jpg)

**Comment by tkphd** [comment]
Mumtahinah Sristy submission 1 via @annajiat 

![mumtahinah_sristy](https://user-images.githubusercontent.com/2179347/99453905-a0827400-28f3-11eb-8d61-49702defae76.png)

**Comment by tkphd** [comment]
Mumtahinah Sristy submission 2 via @annajiat

![mumtahinah_sristy_2](https://user-images.githubusercontent.com/2179347/99453997-cad43180-28f3-11eb-8662-7d8be6274586.png)

**Comment by tkphd** [comment]
Sakib Hassan via @annajiat

![sakib_hassan](https://user-images.githubusercontent.com/2179347/99454090-eb9c8700-28f3-11eb-8e30-7ea14b694cdb.jpg)

**Comment by tkphd** [comment]
Shouvik Barua via @annajiat

![shouvik_barua](https://user-images.githubusercontent.com/2179347/99454171-0a028280-28f4-11eb-9af6-b2a2bf720f7b.png)

**Comment by tkphd** [comment]
Tanzimul Haque via @annajiat

![tanzimul_haque](https://user-images.githubusercontent.com/2179347/99454240-26062400-28f4-11eb-926a-605db047568e.jpg)

**Comment by annajiat** [comment]
Here are the banners without background and with white background


- ![hpc (without background) ](https://user-images.githubusercontent.com/3046889/108343839-9d569700-7206-11eb-8f87-ddd5b7a4e51c.png)
 
- ![hpc-01](https://user-images.githubusercontent.com/3046889/108343847-9e87c400-7206-11eb-9ac7-ac7fb1c45de2.png)

**Comment by annajiat** [comment]
As we are adopting the winning designs, I would like to take this opportunity thank you all the volunteers:
@tanzimul260497
@Sa911-rgb
@Shouvik-Barua
@MumtahinahSristy
@mdsabbiralmamon

Thank you.

**Comment by annajiat** [comment]
As Github doesn't support uploading SVG,
Please find the SVG at https://drive.google.com/drive/u/0/folders/1_-mOFqloHBok6y1WfhLzwWV_xlJzW7GS 
Courtesy of @MumtahinahSristy

Please let us know if anything else is needed.

**Comment by ocaisa** [comment]
The logos are up on the website and there are copies in https://github.com/hpc-carpentry/hpc-carpentry.github.io/tree/main/assets/img

Thanks a lot to everyone who submitted a logo, everyone who voted, @annajiat for organising and @MumtahinahSristy for the fantastic logo!
