### ISSUE TITLE
deprecation process

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/hpc-carpentry.old-site#29]
"hpc-carpentry.github.io" is a tedious URL, and we have a better one: [hpc-carpentry.org](https://www.hpc-carpentry.org). This repo should be deprecated in favor of the better URL. 

Deprecation should be a two-step process, after [checks](https://github.com/hpc-carpentry/hpc-carpentry.org/issues/5) have completed.

1. Redirect with a warning and notice to update bookmarks.
2. After 3 months, archive this repo.

**Comment by ocaisa** [comment]
I've cleared out or moved the remaining issues.

I *think* the redirect is easy, we just add an index.html with a redirect and touch a `.nojekyll` file

**Comment by ocaisa** [comment]
Actually we could probably be more clever than this. We can add a deprecation corner banner in the template, and just use
```
<meta http-equiv="refresh" content="5;URL=https://www.hpc-carpentry.org/">
```
in the header on the main landing page. That would leave any existing links working during the deprecation.  I'll look into this.

**Comment by ocaisa** [comment]
Deprecation is now complete, I'm closing this issue and archiving this repo
